
name: Publish Package to npmjs
on: 
  push:
    branches:
    - "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  
          token: ${{ secrets.WRITE_TOKEN }}

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}
        with:
          skip-tag:  'true'

      - name: Install dependencies
        run: yarn install --no-progress && yarn lint && yarn test && yarn build

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow files
          scope: '@openbeta'
      - run: yarn
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
